spring:
  cloud:
    gateway:
      routes:
        - id: r1 # Route 1 for agences
          uri: http://localhost:8088/ # Target URI for this route
          predicates:
            - Path=/orders/**
        - id: r2 # Route 2 for commercant
          uri: http://localhost:8087/ # Target URI for this route
          predicates:
            - Path=/products/**
        - id: r2 # Route 2 for comptes
          uri: http://localhost:8089/ # Target URI for this route
          predicates:
            - Path=/comptes/**
      globalcors:
        corsConfigurations:
          '[/**]': # Allow CORS for all paths
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
